#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# 判断home是否为空，为空则复制
if [[ `ls $HOME | wc -l` -eq 0 ]];then
    cp -r /config.bak/. /config/
fi

# 第一次运行复制文件
if [[ ! -f $HOME/.config/openbox/menu.xml ]]; then
    mkdir -p $HOME/.config/openbox && \
    cp /defaults/menu.xml $HOME/.config/openbox/menu.xml && \
    lsiown -R abc:abc /config/.config
fi

# 更改权限
lsiown -R abc:abc /$HOME

